# Generated by Django 4.1 on 2024-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient_mass',
            field=models.IntegerField(default=0),
        ),
    ]
